### ISSUE TITLE
Block in title appears to fail

### ISSUE THREAD

**Issue by MattIPv4** [posthtml/posthtml-extend#31]
With posthtml@0.13.4 & posthtml-extend@0.5.0, the following works just fine:

```html
<html>
    <head>
        <title><block name="title"></block> — Github</title>
    </head>

    <body>
        <div class="content">
           <block name="content"></block>
        </div>
    </body>
</html>
```

```html
<extends src="base.html">
    <block name="title">How to use posthtml-extend</block>
    <block name="content">Read the documentation</block>
</extends>
```

With posthtml@0.13.4 & posthtml-extend@**0.5.1**, it errors:

```text
[posthtml-extend] Unexpected block "title"
    at getError (node_modules/posthtml-extend/lib/extend.js:228:12)
    at mergeExtendsAndLayout (node_modules/posthtml-extend/lib/extend.js:156:23)
    at node_modules/posthtml-extend/lib/extend.js:91:31
    at node_modules/posthtml/lib/api.js:91:45
    at traverse (node_modules/posthtml/lib/api.js:105:26)
    at Array.match (node_modules/posthtml/lib/api.js:90:7)
    at handleExtendsNodes (node_modules/posthtml-extend/lib/extend.js:81:16)
    at node_modules/posthtml-extend/lib/extend.js:45:16
    at node_modules/parcel-bundler/node_modules/posthtml/lib/index.js:188:14
    at tryCatch (node_modules/parcel-bundler/node_modules/posthtml/lib/index.js:271:12)
```

**Comment by Scrum** [comment]
@MattIPv4 Hi, thanks for contacting us. The reason lies in the parsing that we recently updated.

Now we are solving this [problem](https://github.com/fb55/htmlparser2/issues/642), I can offer as an alternative to use such a block

**base.html**
```html
<head>
  <block name="title"><title> — Github</title></block>
</head>
```

**index.html**
```html
<block name="title"><title>How to use posthtml-extend</title></block>
```
